name: Run Tests
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.6
        poetry_version: 1.0.3
        working_directory: ./python3
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.6
        poetry_version: 1.0.3
        working_directory: ./python3
        args: run coverage run --omit='./nayvy_vim_if/*,./tests/**/*' --source=. -m pytest -vv --durations=10
    - name: coverage report
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.6
        poetry_version: 1.0.3
        working_directory: ./python3
        args: run coverage report -m



